/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import { useGLTF } from '@react-three/drei'

export function Fish(props) {
  const { nodes, materials } = useGLTF('/models/fish.gltf')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Mesh_fish.geometry} material={materials.pink} />
      <mesh geometry={nodes.Mesh_fish_1.geometry} material={materials.greyLight} />
      <mesh geometry={nodes.Mesh_fish_2.geometry} material={materials._defaultMat} />
    </group>
  )
}

useGLTF.preload('/fish.gltf')
