/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import { useGLTF } from '@react-three/drei'
import { useEffect, useRef } from 'react'
import * as THREE from 'three'

const newMaterial = new THREE.MeshBasicMaterial({ color: 'red' })

const pink = new THREE.Color('rgb(100%, 53%, 56%)')
const grey = new THREE.Color('rgb(84%, 90%, 95%)')
const defaultColor = new THREE.Color( 1, 1, 1 )

export function Fish(props) {
  const model = useRef(null)
  const { nodes, materials } = useGLTF('/models/fish.gltf')

  console.log(materials)



  return (
    <group ref={model} {...props} dispose={null}>
      <mesh geometry={nodes.Mesh_fish.geometry} material={new THREE.MeshBasicMaterial( { color: pink } )} />
      <mesh geometry={nodes.Mesh_fish_1.geometry} material={new THREE.MeshBasicMaterial( { color: grey } )} />
      <mesh geometry={nodes.Mesh_fish_2.geometry} material={new THREE.MeshBasicMaterial({ color: defaultColor })} />
    </group>
  )
}

useGLTF.preload('/fish.gltf')
